---
name: Scalar-Cycle-Manual
version: 0.02
author:
  - 'Khemir Nadim ibn Hamouda. <nadim@khemir.net>'
abstract: "Manualy cycle through a list of values\n"
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::Compare: 0
  Data::TreeDumper: 0
  Readonly: 0
  Sub::Exporter: 0
  Test::Block: 0
  Test::Dependencies: 0
  Test::Distribution: 0
  Test::Exception: 0
  Test::NoWarnings: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Spelling: 0
  Test::Strict: 0
  Test::Warn: 0
  version: 0.5
provides:
  Scalar::Cycle::Manual:
    file: lib/Scalar/Cycle/Manual.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
